name: Readd Issue Label
description: Remove and readd issue label

inputs:
  issue-number:
    required: true
  label:
    required: true
  repo:
    default: ${{ github.repository }}
  token:
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Remove label
      run: |
        curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ inputs.repo }}/issues/${{ inputs.issue-number }}/labels/${{ inputs.label }}"
      shell: bash

    - name: Readd label
      run: |
        curl --fail-with-body -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ inputs.repo }}/issues/${{ inputs.issue-number }}/labels" \
          -d "$(jq -n --arg l "${{ inputs.label }}" '{ labels: [$l] }')"
      shell: bash
