name: Run Tests
description: Run project tests and generate coverage report

inputs:
  build-dir:
    default: 'build'
  source-dir:
    default: '.'
  valgrind:
    default: 'false'
  coverage:
    default: 'false'
  gcov:
    default: 'gcov'

runs:
  using: composite
  steps:
    - name: Run tests
      id: run_tests
      working-directory: ${{ inputs.source-dir }}
      run: meson test --print-errorlogs -C ${{ inputs.build-dir }}
      shell: bash

    - name: Run tests with valgrind
      id: run_tests_valgrind
      working-directory: ${{ inputs.source-dir }}
      if: ${{ inputs.valgrind == 'true' }}
      run: |
          VALGRIND_CMD="valgrind"
          VALGRIND_CMD+=" --leak-check=full --show-leak-kinds=all"
          VALGRIND_CMD+=" --track-origins=yes --errors-for-leak-kinds=all"
          VALGRIND_CMD+=" --max-stackframe=3145916 --error-exitcode=1"
          meson test \
            --wrap="$VALGRIND_CMD" \
            -t 4 \
            --print-errorlogs \
            -C ${{ inputs.build-dir }}
      shell: bash

    - name: Calculate coverage
      id: calculate_coverage
      working-directory: ${{ inputs.source-dir }}
      if: ${{ inputs.coverage == 'true' }}
      run: |
        echo "gcov-executable = ${{ inputs.gcov }}" > gcovr.cfg
        echo -e "filter = ../src/\nfilter = ../plugins/" >> gcovr.cfg
        ninja coverage-xml -C ${{ inputs.build-dir }}
      shell: bash
