name: Add Git Trailers to PR commits

on:
  workflow_call:
    inputs:
      plugin:
        type: string
        default: ''
    secrets:
      GIT_CLONE_PAT:
        required: false
      ORG_PAT:
        required: true

jobs:
  git-trailers:
    runs-on: [self-hosted, x86_64]

    steps:
      - name: Checkout .github directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
          repository: ${{ (inputs.plugin != '' && 'nubificus/vaccel') || '' }}
          ref: ${{ (inputs.plugin != '' && 'ci_rework_plugin') || '' }}

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace
        with:
          fetch-depth: 0
          remote-actions-repo: ${{ (inputs.plugin != '' && 'nubificus/vaccel') || '' }}
          token: ${{ secrets.GIT_CLONE_PAT || github.token }}

      - name: Append git trailers
        uses: nubificus/git-trailers@main
        with:
          user_info: ${{ github.workspace }}/.contributors.yaml

      - name: Trigger required tests re-run
        run: |
          curl -X DELETE \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.ORG_PAT}}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/ok-to-test"
          sleep 5
          curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.ORG_PAT}}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
              -d '{
                  "labels": ["ok-to-test"]
              }'
