name: CI

on:
  pull_request:
    branches: ["main"]
    types:
      - synchronize
      - labeled


  workflow_dispatch:

jobs:
  test:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    runs-on: [self-hosted, "${{ matrix.archconfig }}", gcc, lite, "2204"]

    strategy:
      matrix:
        archconfig: [x86_64, aarch64, armv7l]
        build_type: [debug, release]
      fail-fast: false

    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - name: Cleanup previous jobs
        run: |
          echo "Cleaning up previous runs"
          sudo rm -rf ${{ github.workspace }}/*
          sudo rm -rf ${{ github.workspace }}/.??*

      - name: Install project dependencies
        id: install_dependencies
        run: |
          sudo apt update && sudo apt-get install -y lcov gcc-12 g++-12 ninja-build
          sudo pip install meson

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build project
        id: build_vaccelrt
        run: |
          meson setup \
            --prefix=${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt \
            --buildtype=${{matrix.build_type}} \
            -Dexamples=enabled \
            build_${{matrix.build_type}}
          meson compile -C build_${{matrix.build_type}}
          meson install -C build_${{matrix.build_type}}

      - name: Build vAccel plugins
        id: build_plugins
        run: |
          meson setup \
            --reconfigure \
            -Dplugins=enabled \
            build_${{matrix.build_type}}
          meson compile -C build_${{matrix.build_type}}
          meson install -C build_${{matrix.build_type}}

      - name: Run examples
        id: run_examples
        env:
          VACCEL_DEBUG_LEVEL: 4
        run: |
          export LD_LIBRARY_PATH=${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt/lib/$($CC -print-multiarch)
          export VACCEL_BACKENDS=${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt/lib/$($CC -print-multiarch)/libvaccel-noop.so
          cd ${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt
          sudo mkdir -p /run/user/1001
          sudo chown -R runner /run/user/1001
          ./bin/classify share/vaccel/images/example.jpg 1
          ./bin/classify_generic share/vaccel/images/example.jpg 1
          ./bin/detect share/vaccel/images/example.jpg 1
          ./bin/detect_generic share/vaccel/images/example.jpg 1
          ./bin/pose share/vaccel/images/example.jpg 1
          ./bin/pose_generic share/vaccel/images/example.jpg 1
          ./bin/segment share/vaccel/images/example.jpg 1
          ./bin/segment_generic share/vaccel/images/example.jpg 1
          ./bin/depth share/vaccel/images/example.jpg 1
          ./bin/depth_generic share/vaccel/images/example.jpg 1
          ./bin/sgemm
          ./bin/sgemm_generic
          ./bin/minmax 262144 ./share/vaccel/input/input_262144.csv 5 100
          ./bin/minmax_generic 262144 ./share/vaccel/input/input_262144.csv 5 100
          ./bin/pynq_vector_add
          ./bin/pynq_array_copy
          ./bin/pynq_parallel
          ./bin/torch_inference ./share/vaccel/images/example.jpg ./share/vaccel/models/torch
          ./bin/single_model share/vaccel/models/tf/frozen_graph.pb
          ./bin/tf_saved_model share/vaccel/models/tf/lstm2
          ./bin/tf_inference share/vaccel/models/tf/lstm2
          ./bin/tflite_inference share/vaccel/models/tf/lstm2.tflite
          ./bin/mbench 1 share/vaccel/images/example.jpg

      - name: Run exec examples
        id: run_exec_examples
        env:
          VACCEL_DEBUG_LEVEL: 4
        run: |
          export LD_LIBRARY_PATH=${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt/lib/$($CC -print-multiarch)
          export VACCEL_BACKENDS=${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt/lib/$($CC -print-multiarch)/libvaccel-exec.so
          cd ${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt
          #sudo mkdir -p /run/user/1001
          #sudo chown -R runner /run/user/1001
          export TESTLIB_DIR=lib/$($CC -print-multiarch)
          ./bin/exec_with_res $TESTLIB_DIR/libmytestlib.so 1
          ./bin/exec_helpers $TESTLIB_DIR/libmytestlib.so 1
          ./bin/exec_helpers_nonser $TESTLIB_DIR/libmytestlib.so 1

      - name: Run Tests
        id: run_tests
        run: |
          cd ${{github.workspace}}
          meson setup \
            --reconfigure \
            -Dtests=enabled \
            build_${{matrix.build_type}}
          meson compile -C build_${{matrix.build_type}}
          meson test --print-errorlogs -C build_${{matrix.build_type}}

      - name: Clean-up
        run: sudo rm -rf artifacts build_${{ matrix.build_type }}

  utils:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/utils.yml
    needs: [test]
