name: Upload Coverage Report

on:
  workflow_call:

jobs:
  coverage_upload:
    runs-on: [self-hosted, "x86_64", gcc, lite, "2204"]

    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - name: Checkout .github directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace

      - name: Build project
        id: build_vaccelrt
        uses: ./.github/actions/build
        with:
          build-dir: build
          coverage: 'true'
          options: 'tests=enabled'

      - name: Generate coverage report
        id: generate_coverage
        uses: ./.github/actions/run-tests
        with:
          build-dir: build
          coverage: 'true'
          gcov: 'gcov-12'

      - name: Produce markdown file
        run: |
          pycobertura show "$(find build -name "coverage*.xml")" --format markdown --output "${{github.workspace}}/docs/coverage/src_coverage/coverage.md"
        shell: bash

      - name: Configure Git
        run: |
          echo "Setting up git configuration..."
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Push to vaccel-docs
        uses: datalbry/copy_folder_to_another_repo_action@1.0.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.NBFC_BUILDER_TOKEN }}
        with:
          source_folder: "./docs/coverage/src_coverage"
          destination_repo: "nubificus/vaccel-docs"
          destination_folder: "docs/coverage"
          user_email: "jlima@nubificus.co.uk"
          user_name: "jlima"
          commit_msg: "[GHA] Update the coverage files"
          destination_branch: "main"
