name: coverage_upload

on:
  workflow_call:

jobs:
  coverage_upload:
    runs-on: [self-hosted, "x86_64", gcc, lite, "2204"]
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}

    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies for tests
        id: install_dependencies
        run: |
          sudo apt update && sudo apt-get install -y lcov gcc-12 g++-12 ninja-build libclang-dev
          sudo pip install meson gcovr pycobertura

      - name: Run tests
        id: run_tests
        run: |
          meson setup \
            -Db_coverage=true \
            -Dtests=enabled \
            build
          meson compile -C build
          meson test --print-errorlogs -C build

      - name: Generate coverage report
        run: |
          echo "gcov-executable = gcov-12" > gcovr.cfg
          echo -e "filter = ../src/\nfilter = ../plugins/" >> gcovr.cfg
          ninja coverage-xml -C build
          cp build/meson-logs/coverage.xml ${{github.workspace}}/docs/coverage/coverage.xml
        shell: bash

      - name: Produce markdown file
        run: pycobertura show ${{github.workspace}}/docs/coverage/coverage.xml --format markdown --output ${{github.workspace}}/docs/coverage/src_coverage/coverage.md
        shell: bash

      - name: Configure Git
        run: |
          echo "Setting up git configuration..."
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Push to vaccel-docs
        uses: datalbry/copy_folder_to_another_repo_action@1.0.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.NBFC_BUILDER_TOKEN }}
        with:
          source_folder: "./docs/coverage/src_coverage"
          destination_repo: "nubificus/vaccel-docs"
          destination_folder: "docs/coverage"
          user_email: "jlima@nubificus.co.uk"
          user_name: "jlima"
          commit_msg: "[GHA] Update the coverage files"
          destination_branch: "main"
