name: Build and Verify

on:
  pull_request:
    branches: ["main"]
    types:
      - synchronize
      - labeled

  workflow_dispatch:

jobs:
  test_build:
    name: Test Build
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/test-build.yml

  verify_build:
    name: Verify Build
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/verify-build.yml

  validate_code_and_commits:
    name: Validate Code and Commits
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/validate-code-and-commits.yml
