name: Build and Verify

on:
  pull_request:
    branches: ["main"]
    types:
      - synchronize
      - labeled

  workflow_dispatch:

jobs:
  test_build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/test-build.yml

  verify_build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/verify-build.yml

  validate_source:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/validate-source.yml
