name: Add Git Trailers to PR commits

on:
  pull_request_review:
    types: [submitted]

jobs:
  git-trailers:
    name: Add Git Trailers to PR commits
    if: ${{ github.event.review.state == 'approved' }}
    uses: ./.github/workflows/add-git-trailers.yml
    secrets: inherit
