name: Add Git Trailers for PRs

on:
  pull_request_review:
    types: [submitted]

jobs:
  git-trailers:
    runs-on: [self-hosted, x86_64]
    if: ${{ github.event.review.state == 'approved' }}

    steps:
      - name: Checkout .github directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace
        with:
          fetch-depth: 0

      - name: Append git trailers
        uses: nubificus/git-trailers@main
        with:
          user_info: ${{ github.workspace }}/.contributors.yaml

      - name: Trigger required tests re-run
        run: |
          curl -X DELETE \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.ORG_PAT}}" \
              "https://api.github.com/repos/${{ github.repository }}/labels/ok-to-test"
          sleep 5
          curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.ORG_PAT}}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
              -d '{
                  "labels": ["ok-to-test"]
              }'
