name: Test Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: nubificus/vaccel-deps:latest
      volumes:
        - /tmp/vaccel:/vaccel

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory /vaccel/build_${{ matrix.build_type }}

    - name: Configure CMake
      working-directory: /vaccel/build_${{ matrix.build_type }}
      run: |
         cmake $GITHUB_WORKSPACE \
                -DCMAKE_INSTALL_PREFIX=/vaccel/artifacts/${{ matrix.build_type }}/opt \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DBUILD_PLUGIN_JETSON=ON \
                -DBUILD_PLUGIN_VIRTIO=ON
                

    - name: Build runtime
      working-directory: /vaccel/build_${{ matrix.build_type }}
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      working-directory: /vaccel/build_${{ matrix.build_type }}
      run: |
        make test
        make install -C src
        make install -C plugins

    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: vaccelrt-${{ github.head_ref }}-${{ matrix.build_type }} 
        path: /vaccel/artifacts/${{ matrix.build_type }}/*
