name: Upload new release

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, "x86_64" ]

    steps:
    - name: Fetch vaccelrt x86_64
      uses: cloudkernels/minio-download@v2
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ env.NBFC_S3_ACCESS }}
        secret-key: ${{ env.NBFC_S3_SECRET }}
        local-path: /github/workspace/artifacts/vaccelrt-${{ github.ref }}-x86_64.tar.gz
        remote-path: nbfc-assets/github/vaccelrt/main/x86_64/Release-tar/vaccelrt-${{github.ref}}.tar.gz

    - name: Fetch vaccelrt aarch64
      uses: cloudkernels/minio-download@v2
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ env.NBFC_S3_ACCESS }}
        secret-key: ${{ env.NBFC_S3_SECRET }}
        local-path: /github/workspace/artifacts/vaccelrt-${{ github.ref }}-aarch64.tar.gz
        remote-path: nbfc-assets/github/vaccelrt/main/aarch64/Release-tar/vaccelrt-${{github.ref}}.tar.gz

    - name: Fetch vaccelrt aarch32
      uses: cloudkernels/minio-download@v2
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ env.NBFC_S3_ACCESS }}
        secret-key: ${{ env.NBFC_S3_SECRET }}
        local-path: /github/workspace/artifacts/vaccelrt-${{ github.ref }}-aarch32.tar.gz
        remote-path: nbfc-assets/github/vaccelrt/main/aarch32/Release-tar/vaccelrt-${{github.ref}}.tar.gz

    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{secrets.NBFC_BUILDER_TOKEN}}
        automatic_release_tag: ${{github.event.inputs.tag}}
        title: "vAccelrt test release ${{github.event.inputs.tag}}"
        files: |
          artifacts/vaccelrt-${{ github.ref }}-x86_64.tar.gz
          artifacts/vaccelrt-${{ github.ref }}-aarch64.tar.gz
          artifacts/vaccelrt-${{ github.ref }}-aarch32.tar.gz

