name: Test Pull Request

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: [cloud, "${{ matrix.archconfig }}" ]

    strategy:
      matrix:
        archconfig: [ x86_64, aarch64 ]
        build_type: [Debug, Release]
      fail-fast: false

    steps:
    - name: Cleanup pervious jobs
      run: |
        echo "Cleaning up previous runs"
        sudo rm -rf ${{ github.workspace }}/*
        sudo rm -rf ${{ github.workspace }}/.??*

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Find SHA
      run: |
        if [[ "${{github.event.pull_request.head.sha}}" != "" ]]
        then
          echo "ARTIFACT_SHA=$(echo ${{github.event.pull_request.head.sha}})" >> $GITHUB_ENV
        else
          echo "ARTIFACT_SHA=$(echo ${{github.sha}})" >> $GITHUB_ENV
        fi

    - name: Install deps
      id: install-deps
      run: |
        sudo apt update
        sudo apt install -y cmake

    - name: Build project
      id: build_vaccelrt
      run: |
        cargo --version
        rustc --version
        mkdir -p build_${{matrix.build_type}}
        cd build_${{matrix.build_type}}
        cmake ${{github.workspace}} \
          -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DBUILD_PLUGIN_JETSON=ON \
          -DBUILD_PLUGIN_VIRTIO=ON \
          -DBUILD_PLUGIN_VSOCK=ON \
          -DENABLE_TESTS=ON \
          -DBUILD_EXAMPLES=ON && \
        cmake --build . --config ${{matrix.build_type}} && \
        make test && \
        make install -C src && \
        make install -C plugins && \
        make install -C examples

    - name: Build vAccel bindings
      run: |
        cd build_${{matrix.build_type}}
        cmake ${{github.workspace}} \
          -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/artifacts/${{matrix.archconfig}}/${{matrix.build_type}}/opt \
          -DBUILD_BINDINGS=ON
        make -C bindings

    - name: Upload artifact to s3
      uses: cloudkernels/minio-upload@master
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ secrets.AWS_ACCESS_KEY }}
        secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        local-path: artifacts/${{ matrix.archconfig }}/${{ matrix.build_type }}/opt
        remote-path: nbfc-assets/github/vaccelrt/${{ env.ARTIFACT_SHA }}/${{ matrix.archconfig }}/${{ matrix.build_type }}/
    - name: Clean-up
      run: sudo rm -rf artifacts build_${{ matrix.build_type }}
