name: Testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  testing:
    runs-on: ["self-hosted", "${{ matrix.architecture }}", gcc, lite, 2204 ]
  
    concurrency:
      group: ${{ matrix.architecture }}

    strategy:
      fail-fast: false
      matrix:
        architecture: [ x86_64, aarch64, armv7l]
        build_type: [Debug, Release]
      
        
    steps:
      - name: Cleanup pervious jobs
        run: |
          echo "Cleaning up previous runs"
          sudo rm -rf ${{ github.workspace }}/*
          sudo rm -rf ${{ github.workspace }}/.??*

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: true 
          submodules: recursive
          
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install -y lcov cmake gcc g++ libclang-dev
      
      - name: Check g++ version
        run : |
          gcc --version
          
      - name: Create dir
        run : |
          if [ "${{ matrix.architecture }}" = "armv7l" ]; then
            sudo mkdir /run/user/1001/ 
            sudo chown runner /run/user/1001
          fi
       
      - name: Set up CMake and run tests
        run: |
          export CXX=g++
          mkdir -p build
          cd build
          cmake ../ -DBUILD_PLUGIN_NOOP=ON -DENABLE_TESTS=ON -DBUILD_EXAMPLES=ON -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          make
          make test ARGS="-V"
          cd ../
        shell: bash
        env:
          ARCHITECTURE: ${{ matrix.architecture }}


  github_runners:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        architecture: [x86_64, aarch64, armv7l]
        build_type: [Debug, Release]

    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: true 
          submodules: recursive

        
      - name: Install dependencies
        run: sudo apt-get install lcov
      
      - name: Check g++ version
        run : |
          gcc --version

      - name: Set up CMake and run tests
        run: |
          export CXX=g++
          rm -rf build
          mkdir -p build
          cd build
          cmake ../ -DBUILD_PLUGIN_NOOP=ON -DENABLE_TESTS=ON -DBUILD_EXAMPLES=ON -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          make
          make test ARGS="-V"
          cd ../
        shell: bash
        env:
          ARCHITECTURE: ${{ matrix.architecture }}
