name: Validate Source Code and Commit Messages

on:
  workflow_call:

jobs:
  linter_typos:
    name: Spell Check Repo
    runs-on: [self-hosted, "x86_64", gcc, lite, "2204"]

    steps:
      - name: Checkout .github directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace

      - name: Spell check
        uses: crate-ci/typos@master
        with:
          config: .github/linters/typos.toml

  linter_cppcheck:
    name: Lint C/C++ (cppcheck)
    runs-on: [self-hosted, "x86_64", gcc, lite, "2204"]

    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - name: Checkout .github directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace

      - name: Configure project
        uses: ./.github/actions/build
        with:
          build-dir: build
          build: 'false'
          options: 'auto_features=enabled'

      - name: Run cppcheck
        run: |
          cppcheck --project=build/compile_commands.json \
            -itest -ithird-party -isubprojects \
            --suppressions-list=.github/linters/cppcheck.txt \
            --error-exitcode=2

  linter_cpp_linter:
    name: Lint C/C++ (cpp-linter)
    runs-on: [self-hosted, "x86_64", gcc, lite, "2204"]

    permissions:
      pull-requests: write
      contents: read

    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - name: Checkout .github directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace

      - name: Configure project
        id: configure_vaccelrt
        uses: ./.github/actions/build
        with:
          build-dir: build
          build: 'false'
          options: 'auto_features=enabled'

      - uses: cpp-linter/cpp-linter-action@v2
        id: cpp_linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'  # Use .clang-format config file
          tidy-checks: '' # Use .clang-tidy config file
          ignore: 'build|subprojects'
          database: build
          thread-comments: ${{ github.event_name == 'pull_request' && 'true' }}
          format-review: ${{ github.event_name == 'pull_request' && 'true' }}
          version: 18

      - name: Fail on error
        if: steps.cpp_linter.outputs.clang-format-checks-failed > 0
        run: exit 1

  linter_super_linter:
    name: Lint Python/Shell/Dockerfiles/GHActions/Markdown/YAML
    runs-on: [self-hosted, "x86_64", gcc, lite, "2204"]

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout .github directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace
        with:
          fetch-depth: 0

      - name: linter
        uses: super-linter/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true

  linter_commitlint:
    name: Lint Commit Messages
    runs-on: [self-hosted, "x86_64", gcc, lite, "2204"]

    steps:
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .github/linters/commitlintrc.yml

  coverage_diff:
    name: Generate Coverage Report
    needs:
      - linter_typos
      - linter_cppcheck
      - linter_cpp_linter
      - linter_super_linter
      - linter_commitlint
    runs-on: [self-hosted, "x86_64", gcc, lite, "2204"]

    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - name: Checkout .github directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace

      - name: Build project
        id: build_vaccelrt
        uses: ./.github/actions/build
        with:
          build-dir: build
          coverage: 'true'
          options: 'tests=enabled'

      - name: Generate coverage report
        id: generate_coverage
        uses: ./.github/actions/run-tests
        with:
          build-dir: build
          coverage: 'true'
          gcov: 'gcov-12'

      ### TODO: add cache/artifacts to speed up this whole file

      - name: Clone project @main
        id: clone_vaccelrt_main
        run: git clone --recursive https://github.com/cloudkernels/vaccelrt vaccelrt_main

      - name: Build project @main
        id: build_vaccelrt_main
        uses: ./.github/actions/build
        with:
          build-dir: build
          source-dir: vaccelrt_main
          coverage: 'true'
          options: 'tests=enabled'

      - name: Generate coverage report @main
        id: generate_coverage_main
        uses: ./.github/actions/run-tests
        with:
          build-dir: build
          source-dir: vaccelrt_main
          coverage: 'true'
          gcov: 'gcov-12'

      - name: Calculate coverage diff
        id: calculate_coverage_diff
        run: |
          # Temporarily ignore coverage changes, just print out the exit code
          # https://github.com/aconrad/pycobertura?tab=readme-ov-file#diff-exit-codes
          pycobertura diff "$(find vaccelrt_main/build -name "coverage*.xml")" "$(find build -name "coverage*.xml")" --no-color --no-source -f markdown > coverage_diff.txt  || PYCOB_RESULT="$?"
          echo "pycobertura exited with $PYCOB_RESULT"
          echo '```' > temp_file && cat ./coverage_diff.txt >> temp_file && echo -e '\n```' >> temp_file && mv temp_file ./coverage_diff.txt
          rm -rf vaccelrt_main
        shell: bash

      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./coverage_diff.txt

      - name: Clean-up
        run: sudo rm -rf artifacts build
